BEGIN;

-- email_cidr_reports: official CIDR report data gathered from the NANOG list
--
-- row size: 32 bytes (+ netname)
-- table size: (675 x 32) rows; ~0.6 MB
CREATE TABLE email_cidr_reports (
    id                  serial      PRIMARY KEY,
    date                date        NOT NULL,
    origin_as           bigint      NOT NULL,
    netsnow             integer     NOT NULL,
    netgain             integer     NOT NULL,
    insert_date         timestamp   NOT NULL, -- UTC
    netname             text
);

-- gen_cidr_reports: CIDR report data generated by my cidr-report program
--
-- row size: 52 bytes (+ notes)
-- table size: (667 x 30k) rows; ~1 GB
CREATE TABLE gen_cidr_reports (
    id                  serial      PRIMARY KEY,
    date                date        NOT NULL,
    origin_as           bigint      NOT NULL,
    rank_netgain        integer     NOT NULL, -- AS' rank on that week's report
    rank_netsnow        integer     NOT NULL, -- AS' rank by netsnow
    nets_current        integer     NOT NULL, -- netsnow
    nets_withdrawn      integer     NOT NULL,
    nets_aggregated     integer     NOT NULL,
    nets_announced      integer     NOT NULL, -- netsaggr
    nets_reduced        integer     NOT NULL, -- netgain
    gen_date            timestamp   NOT NULL, -- UTC
    notes               text                  -- i.e. MOAS notes
);

-- peers: allows unique peer (as, ip) combinations to be referenced via a
-- single value
--
-- row size: 16 bytes
-- table size: 193 rows
CREATE TABLE peers (
    id                  serial      PRIMARY KEY,
    peer_as             bigint      NOT NULL,
    peer_ip             ip4         NOT NULL
);

-- peer_table_summaries: number of prefixes originated by each AS visible from
-- each Route Views peer (i.e. PPAPP data)
--
-- row size: 28 bytes (+ notes)
-- table size: (667 x 1M) rows; ~19 GB
CREATE TABLE peer_table_summaries (
    id                  bigserial   PRIMARY KEY,
    date                date        NOT NULL,
    origin_as           bigint      NOT NULL,
    peer_id             integer     NOT NULL    REFERENCES peers(id),
    prefix_count        integer     NOT NULL,
    notes               text        -- i.e. origin with multiple-AS AS_SETs?
);

-- prefix_origins: records the origin of each prefix as seen by each peer,
-- each time the announcements change over time
--
-- row size: 36 bytes (+ notes)
-- table size: (667 x 1M) rows; ~24 GB
CREATE TABLE prefix_origins (
    id                  bigserial   PRIMARY KEY,
    prefix              ip4r        NOT NULL,
    peer_id             integer     NOT NULL    REFERENCES peers(id),
    origin_as           bigint      NOT NULL,
    norm_as_path        text        NOT NULL,
    raw_as_path         text        NOT NULL,
    date_effective      date        NOT NULL,
--  weeks_seen: 1 = visible, 0 = not visible; MSB = week 0 ... LSB = week N
    weeks_seen          bit varying NOT NULL
);

COMMIT;