library("zoo")

cidr_report <- read.csv("peras.csv")
pdf("7018_plots.pdf", paper="USr", width=10, height=7.5)
par(mfrow=c(3,1))
plot(cidr_report$as7018_rank,    xlab="week", ylab="AS7018 Rank", type="l")
plot(cidr_report$as7018_netgain, xlab="week", ylab="AS7018 NetGain", type="l")
plot(cidr_report$as7018_netsnow, xlab="week", ylab="AS7018 NetsNow", type="l")
dev.off()
pdf("6389_plots.pdf", paper="USr", width=10, height=7.5)
par(mfrow=c(3,1))
plot(cidr_report$as6389_rank,    xlab="week", ylab="AS6389 Rank", type="l")
plot(cidr_report$as6389_netgain, xlab="week", ylab="AS6389 NetGain", type="l")
plot(cidr_report$as6389_netsnow, xlab="week", ylab="AS6389 NetsNow", type="l")
dev.off()
pdf("4323_plots.pdf", paper="USr", width=10, height=7.5)
par(mfrow=c(3,1))
plot(cidr_report$as4323_rank,    xlab="week", ylab="AS4323 Rank", type="l")
plot(cidr_report$as4323_netgain, xlab="week", ylab="AS4323 NetGain", type="l")
plot(cidr_report$as4323_netsnow, xlab="week", ylab="AS4323 NetsNow", type="l")
dev.off()
pdf("701_plots.pdf", paper="USr", width=10, height=7.5)
par(mfrow=c(3,1))
plot(cidr_report$as701_rank,    xlab="week", ylab="AS701 Rank", type="l")
plot(cidr_report$as701_netgain, xlab="week", ylab="AS701 NetGain", type="l")
plot(cidr_report$as701_netsnow, xlab="week", ylab="AS701 NetsNow", type="l")
dev.off()

pdf("diff_plots.pdf", paper="USr", width=10, height=7.5)
par(mfrow=c(20,1), mar=c(0,4,0,0))
###
plot(cidr_report$as701_rank, xlab="", ylab="701",   type="h", ylim=c(0,30), yaxt="n", col="grey")
par(new=TRUE)
plot(rollapply(zoo(cidr_report$as701_netgain/cidr_report$as701_netsnow), 4, (mean)), xlab="", ylab="",   type="l", ylim=c(0,1), axes=F, col="red", lwd=2)
par(new=TRUE)
plot(rollapply(zoo(cidr_report$as701_netgain/cidr_report$cr_netgain), 4, (mean)), xlab="", ylab="",   type="l", ylim=c(0,1), axes=F, col="blue", lwd=2)
par(new=TRUE)
plot(rollapply(zoo(cidr_report$as701_netgain/cidr_report$cr_netsnow), 4, (mean)), xlab="", ylab="",   type="l", ylim=c(0,1), axes=F, col="green", lwd=2)
par(new=FALSE)
###

plot(cidr_report$as7018_rank , xlab="", ylab="7018",  type="h", ylim=c(0,30), yaxt="n")
plot(rollapply(zoo(cidr_report$as7018_rank), 12, (mean)), xlab="", ylab="7018",  type="l", ylim=c(0,30), yaxt="n", col="blue", lwd=4)
par(new=TRUE)
plot(rollapply(zoo(cidr_report$as7018_netgain), 12, (mean)), xlab="", ylab="",   type="l", ylim=c(0,4000), yaxt="n", col="red", lwd=4)
par(new=FALSE)

plot(cidr_report$as4323_rank , xlab="", ylab="4323",  type="h", ylim=c(0,30), yaxt="n")
plot(rollapply(zoo(cidr_report$as4323_rank), 12, (mean)), xlab="", ylab="4323",  type="l", ylim=c(0,30), yaxt="n", col="blue", lwd=4)
par(new=TRUE)
plot(rollapply(zoo(cidr_report$as4323_netgain), 12, (mean)), xlab="", ylab="",   type="l", ylim=c(0,4000), yaxt="n", col="red", lwd=4)
par(new=FALSE)

plot(cidr_report$as4755_rank , xlab="", ylab="4755",  type="h", ylim=c(0,30), yaxt="n")
plot(rollapply(zoo(cidr_report$as4755_rank), 12, (mean)), xlab="", ylab="4755",  type="l", ylim=c(0,30), yaxt="n", col="blue", lwd=4)
par(new=TRUE)
plot(rollapply(zoo(cidr_report$as4755_netgain), 12, (mean)), xlab="", ylab="",   type="l", ylim=c(0,4000), yaxt="n", col="red", lwd=4)
par(new=FALSE)

plot(cidr_report$as17676_rank, xlab="", ylab="17676", type="h", ylim=c(0,30), yaxt="n")
plot(rollapply(zoo(cidr_report$as17676_rank), 12, (mean)), xlab="", ylab="17676", type="l", ylim=c(0,30), yaxt="n", col="blue", lwd=4)
par(new=TRUE)
plot(rollapply(zoo(cidr_report$as17676_netgain), 12, (mean)), xlab="", ylab="",   type="l", ylim=c(0,4000), yaxt="n", col="red", lwd=4)
par(new=FALSE)

plot(cidr_report$as22773_rank, xlab="", ylab="22773", type="h", ylim=c(0,30), yaxt="n")
plot(rollapply(zoo(cidr_report$as22773_rank), 12, (mean)), xlab="", ylab="22773", type="l", ylim=c(0,30), yaxt="n", col="blue", lwd=4)
par(new=TRUE)
plot(rollapply(zoo(cidr_report$as22773_netgain), 12, (mean)), xlab="", ylab="",   type="l", ylim=c(0,4000), yaxt="n", col="red", lwd=4)
par(new=FALSE)

plot(cidr_report$as18566_rank, xlab="", ylab="18566", type="h", ylim=c(0,30), yaxt="n")
plot(rollapply(zoo(cidr_report$as18566_rank), 12, (mean)), xlab="", ylab="18566", type="l", ylim=c(0,30), yaxt="n", col="blue", lwd=4)
par(new=TRUE)
plot(rollapply(zoo(cidr_report$as18566_netgain), 12, (mean)), xlab="", ylab="",   type="l", ylim=c(0,4000), yaxt="n", col="red", lwd=4)
par(new=FALSE)

plot(cidr_report$as4766_rank , xlab="", ylab="4766",  type="h", ylim=c(0,30), yaxt="n")
plot(rollapply(zoo(cidr_report$as4766_rank), 12, (mean)), xlab="", ylab="4766",  type="l", ylim=c(0,30), yaxt="n", col="blue", lwd=4)
par(new=TRUE)
plot(rollapply(zoo(cidr_report$as4766_netgain), 12, (mean)), xlab="", ylab="",   type="l", ylim=c(0,4000), yaxt="n", col="red", lwd=4)
par(new=FALSE)

plot(cidr_report$as4134_rank , xlab="", ylab="4134",  type="h", ylim=c(0,30), yaxt="n")
plot(rollapply(zoo(cidr_report$as4134_rank), 12, (mean)), xlab="", ylab="4134",  type="l", ylim=c(0,30), yaxt="n", col="blue", lwd=4)
par(new=TRUE)
plot(rollapply(zoo(cidr_report$as4134_netgain), 12, (mean)), xlab="", ylab="",   type="l", ylim=c(0,4000), yaxt="n", col="red", lwd=4)
par(new=FALSE)

plot(cidr_report$as1221_rank , xlab="", ylab="1221",  type="h", ylim=c(0,30), yaxt="n")
plot(rollapply(zoo(cidr_report$as1221_rank), 12, (mean)), xlab="", ylab="1221",  type="l", ylim=c(0,30), yaxt="n", col="blue", lwd=4)
par(new=TRUE)
plot(rollapply(zoo(cidr_report$as1221_netgain), 12, (mean)), xlab="", ylab="",   type="l", ylim=c(0,4000), yaxt="n", col="red", lwd=4)
par(new=FALSE)
dev.off()

cidr_freq <- read.csv("cr_freq.csv")
pdf("cdfs.pdf", paper="USr", width=10, height=7.5)
par(mfrow=c(1,2), mar=c(4,2,2,1), oma=c(0,0,10,0))
plot.ecdf(cidr_freq$freq, main="CDF of weeks per AS on the CIDR Report", xlab="weeks", do.points=F, lwd=2, xlim=c(1,700), log="x")
plot.ecdf(cidr_freq$wfreq, main="CDF of rank-weeks per AS on the CIDR Report", xlab="rank-weeks", do.points=F, lwd=2, xlim=c(1,12000), log="x")
#plot.ecdf(cidr_freq$rwfreq, main="CDF of netgain-weeks on CIDR report", xlab="netgain-weeks")
dev.off()
